# -*- coding: utf-8 -*-
"""
gen_pwa.py — 3教科の manifest と service worker を一括生成（subject以外は同一仕様）。
SW は「オフライン起動 / 更新時の旧キャッシュ削除 / 破損時復旧 / 起動不能にならない」を満たす
stale-while-revalidate 方式。
"""
import json, sys, io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

CACHE_VER = "v4"   # ← デプロイのたびに上げると旧キャッシュが確実に破棄される

SUBJECTS = {
  "muki": {
    "name":"無機化学","short":"無機化学","desc":"無機化学の問題演習アプリ（スペース学習）",
    "html":"muki.html","manifest":"manifest.json","sw":"sw.js",
    "theme":"#00c1cc","icon":"muki-icon","cache":"muki",
  },
  "yuki": {
    "name":"有機化学","short":"有機化学","desc":"有機化学の問題演習アプリ（スペース学習）",
    "html":"yuki.html","manifest":"yuki_manifest.json","sw":"yuki_sw.js",
    "theme":"#4966d8","icon":"yuki-icon","cache":"yuki",
  },
  "kobunshi": {
    "name":"高分子化学","short":"高分子化学","desc":"高分子化学の問題演習アプリ（スペース学習）",
    "html":"kobunshi.html","manifest":"kobunshi_manifest.json","sw":"kobunshi_sw.js",
    "theme":"#6db020","icon":"kobunshi-icon","cache":"kobunshi",
  },
}

def manifest(c):
    i192, i512 = f"{c['icon']}-192.png", f"{c['icon']}-512.png"
    return {
        "name": c["name"], "short_name": c["short"], "description": c["desc"],
        "start_url": "./"+c["html"], "scope": "./", "display": "standalone",
        "background_color": "#ffffff", "theme_color": c["theme"],
        "orientation": "portrait-primary", "lang": "ja",
        "icons": [
            {"src": i192, "sizes": "192x192", "type": "image/png", "purpose": "any"},
            {"src": i192, "sizes": "192x192", "type": "image/png", "purpose": "maskable"},
            {"src": i512, "sizes": "512x512", "type": "image/png", "purpose": "any"},
            {"src": i512, "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
        ],
    }

SW_TPL = r"""/* {disp} — PWA Service Worker (auto-generated by gen_pwa.py) */
const CACHE_NAME = '{cache}-{ver}';
const HTML = './{html}';
const ASSETS = ['./{html}', './{manifest}', './{icon}-192.png', './{icon}-512.png'];

self.addEventListener('install', e => {{
  e.waitUntil((async () => {{
    try {{
      const cache = await caches.open(CACHE_NAME);
      // 1件ずつ追加：1つ失敗しても install 全体は失敗させない（堅牢性）
      await Promise.all(ASSETS.map(u => cache.add(u).catch(err => console.warn('[SW] cache miss:', u, err))));
    }} catch (err) {{ console.warn('[SW] install cache error:', err); }}
    await self.skipWaiting();
  }})());
}});

self.addEventListener('activate', e => {{
  e.waitUntil((async () => {{
    // 更新時：現行 CACHE_NAME 以外の旧キャッシュを全削除
    try {{
      const keys = await caches.keys();
      await Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)));
    }} catch (err) {{ console.warn('[SW] activate cleanup error:', err); }}
    await self.clients.claim();
  }})());
}});

self.addEventListener('fetch', e => {{
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;
  // GAS同期・外部リクエストは常にネットワーク（キャッシュ非対象）
  if (url.includes('script.google.com') || !url.startsWith(self.location.origin)) return;

  const isNav = req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html');

  e.respondWith((async () => {{
    let cache = null;
    try {{ cache = await caches.open(CACHE_NAME); }} catch (_) {{}}

    // stale-while-revalidate：キャッシュを即返しつつ裏で更新
    let cached = null;
    try {{ if (cache) cached = await cache.match(req); }} catch (_) {{ cached = null; }}

    const network = fetch(req).then(res => {{
      try {{ if (cache && res && res.status === 200) cache.put(req, res.clone()); }} catch (_) {{}}
      return res;
    }}).catch(() => null);

    if (cached) {{ network; return cached; }}          // 即起動（オフラインでもOK）
    const net = await network;
    if (net) return net;

    // ネットワーク不可＆キャッシュ無し：起動不能を避け、必ずアプリ本体を返す
    if (isNav) {{
      try {{
        const fb = (cache && await cache.match(HTML)) || await caches.match(HTML);
        if (fb) return fb;
      }} catch (_) {{}}
    }}
    return new Response('', {{ status: 504, statusText: 'offline' }});
  }})());
}});
"""

count = 0
for name, c in SUBJECTS.items():
    open(c["manifest"], "w", encoding="utf-8").write(json.dumps(manifest(c), ensure_ascii=False, indent=2) + "\n")
    sw = SW_TPL.format(disp=c["short"], cache=c["cache"], ver=CACHE_VER,
                       html=c["html"], manifest=c["manifest"], icon=c["icon"])
    open(c["sw"], "w", encoding="utf-8").write(sw)
    count += 1
    print(f"[{name}] {c['manifest']} + {c['sw']}  (cache {c['cache']}-{CACHE_VER})")
print(f"done. {count} subjects.")
