/* 無機化学 — PWA Service Worker (auto-generated by gen_pwa.py) */
const CACHE_NAME = 'muki-v6';
const HTML = './muki.html';
const ASSETS = ['./muki.html', './manifest.json', './muki-icon-192.jpg', './muki-icon-512.jpg'];

self.addEventListener('install', e => {
  e.waitUntil((async () => {
    try {
      const cache = await caches.open(CACHE_NAME);
      // 1件ずつ追加：1つ失敗しても install 全体は失敗させない（堅牢性）
      await Promise.all(ASSETS.map(u => cache.add(u).catch(err => console.warn('[SW] cache miss:', u, err))));
    } catch (err) { console.warn('[SW] install cache error:', err); }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', e => {
  e.waitUntil((async () => {
    // 更新時：現行 CACHE_NAME 以外の旧キャッシュを全削除
    try {
      const keys = await caches.keys();
      await Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)));
    } catch (err) { console.warn('[SW] activate cleanup error:', err); }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = req.url;
  // GAS同期・外部リクエストは常にネットワーク（キャッシュ非対象）
  if (url.includes('script.google.com') || !url.startsWith(self.location.origin)) return;

  const isNav = req.mode === 'navigate' || (req.headers.get('accept') || '').includes('text/html');

  e.respondWith((async () => {
    let cache = null;
    try { cache = await caches.open(CACHE_NAME); } catch (_) {}

    // stale-while-revalidate：キャッシュを即返しつつ裏で更新
    let cached = null;
    try { if (cache) cached = await cache.match(req); } catch (_) { cached = null; }

    const network = fetch(req).then(res => {
      try { if (cache && res && res.status === 200) cache.put(req, res.clone()); } catch (_) {}
      return res;
    }).catch(() => null);

    if (cached) { network; return cached; }          // 即起動（オフラインでもOK）
    const net = await network;
    if (net) return net;

    // ネットワーク不可＆キャッシュ無し：起動不能を避け、必ずアプリ本体を返す
    if (isNav) {
      try {
        const fb = (cache && await cache.match(HTML)) || await caches.match(HTML);
        if (fb) return fb;
      } catch (_) {}
    }
    return new Response('', { status: 504, statusText: 'offline' });
  })());
});
